# Generated by Django 2.2.5 on 2019-09-22 04:23

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=55)),
                ('message', models.TextField()),
                ('relation', models.CharField(choices=[('None', 'none'), ('Family', 'family'), ('Friend', 'friday'), ('Professor', 'professor'), ('Student', 'student'), ('Worker', 'work')], default='None', max_length=9)),
            ],
        ),
    ]
